chains:
  noble:
    rpc: ""
    chain-id: "grand-1"
    start-block: 0
    lookback-period: 5
    workers: 8
    tx-memo: "Relayed by Strangelove"
    gas-limit: 200000
    broadcast-retries: 5
    broadcast-retry-interval: 5
    block-queue-channel-size: 1000000
    min-mint-amount: 0
    minter-private-key: ""

  ethereum:
    chain-id: 5
    domain: 0
    rpc: ""
    ws: ""
    message-transmitter: "0x26413e8157CD32011E726065a5462e97dD4d03D9"
    start-block: 0
    lookback-period: 5
    broadcast-retries: 5
    broadcast-retry-interval: 10
    min-mint-amount: 10000000
    metrics-denom: "ETH"
    metrics-exponent: 18
    minter-private-key: ""

  optimism:
    chain-id: 10
    domain: 2
    rpc: ""
    ws: ""
    message-transmitter: "0x4d41f22c5a0e5c74090899e5a8fb597a8842b3e8"
    start-block: 0
    lookback-period: 0
    broadcast-retries: 5
    broadcast-retry-interval: 10
    min-mint-amount: 10000000
    metrics-denom: "ETH"
    metrics-exponent: 18
    minter-private-key: ""

  arbitrum:
    chain-id: 42161
    domain: 3
    rpc: ""
    ws: ""
    message-transmitter: "0xC30362313FBBA5cf9163F0bb16a0e01f01A896ca"
    start-block: 0
    lookback-period: 0
    broadcast-retries: 5
    broadcast-retry-interval: 10
    min-mint-amount: 10000000
    metrics-denom: "ETH"
    metrics-exponent: 18
    minter-private-key: ""

  avalanche:
    chain-id: 43114
    domain: 1
    rpc: ""
    ws: ""
    message-transmitter: "0x8186359af5f57fbb40c6b14a588d2a59c0c29880"
    start-block: 0
    lookback-period: 600
    broadcast-retries: 5
    broadcast-retry-interval: 10
    min-mint-amount: 10000000
    metrics-denom: "AVAX"
    metrics-exponent: 18
    minter-private-key: ""

  solana:
    domain: 5
    rpc: "https://api.mainnet-beta.solana.com"
    ws: ""
    message-transmitter: "CCTPV2Sm4AdWt5296sk4P66VBZ7bEhcARwFaaS9YPbeC"
    token-messenger-minter: "CCTPV2vPZJS2u2BBsUoscuikbYjnpFmbFsvVuJdgUMQe"
    start-block: 0
    lookback-period: 100
    broadcast-retries: 5
    broadcast-retry-interval: 10
    min-mint-amount: 10000000
    metrics-denom: "SOL"
    metrics-exponent: 9
    minter-private-key: ""

# Source domain → destination domains
enabled-routes:
  0: [4, 5]
  1: [4]
  2: [4]
  3: [4]
  4: [0, 1, 2, 3, 5]

circle:
  attestation-base-url: "https://iris-api-sandbox.circle.com/attestations/"
  api-version: "v1"
  fetch-retries: 30
  fetch-retry-interval: 3
  enable-fast-transfer-monitoring: false
  reattest-max-retries: 3
  expiration-buffer-blocks: 100
  allowance-monitor-token: "USDC"
  allowance-monitor-interval: 30

destination-caller-only: false

filters:
  - name: "depositor-whitelist"
    enabled: true
    config:
      provider: "quicknode-kv"
      provider_config:
        api_key: ""
      kv_key: "cctp-depositor-whitelist"
      refresh_interval: 300

processor-worker-count: 16